### PR TITLE
(Feature) New style for xDai network

### LINKED ISSUE #187: (Update) New style for xDai Network
We need to have separate colors and logo for xDai network in Voting DApp. Example (yellow-orange color scheme): https://blockscout.com/poa/dai

### PR DESCRIPTION
**Pull request by gabitoesmiapodo**
Closes #187

**Description:** Updated the dApp to make it able to support different styles, colors, etc. for different networks. 

Fixed a few styling and layout issues here and there.

Added some standard components taken from other POA Network dApps, in hopes to have a more coherent and consistent ecosystem.

Hopefully improved responsive versions.

**What is it:** Update / new feature.

**Additional Info:** I'm attaching a few screen captures to know what to expect from this update.

Ballots section

localhost_3000_poa-dapps-voting laptop with mdpi screen
localhost_3000_poa-dapps-voting ipad
localhost_3000_poa-dapps-voting nexus 6p

New Ballot section

localhost_3000_poa-dapps-voting_new laptop with mdpi screen
localhost_3000_poa-dapps-voting_new ipad
localhost_3000_poa-dapps-voting_new nexus 6p

Mobile menu

localhost_3000_poa-dapps-voting_new nexus 6p 1

Loading component

localhost_3000_poa-dapps-voting_new laptop with mdpi screen

### CODE REVIEW

**Review by vbaranov — CHANGES_REQUESTED** [review]
1. screen shot 2019-01-05 at 22 17 47
2. screen shot 2019-01-05 at 22 15 35
3. screen shot 2019-01-05 at 22 09 39
4. screen shot 2019-01-05 at 22 07 38
5. screen shot 2019-01-05 at 22 06 04
6. screen shot 2019-01-05 at 21 59 02

**Comment by gabitoesmiapodo** [comment]
@vbaranov

- Footer logo should be clickable -> Fixed.
- Should be bolder... -> Fixed.
- New / "New Ballot" title -> Fixed.
- Only first letter should be capitalized -> Fixed.
- First letters should be capitalized -> Fixed.
- Wrong icon order. -> Fixed.

**Comment by varasev** [comment]
Please don't merge this yet. I'll review as well.

**Comment by gabitoesmiapodo** [comment]
@varasev 

Sure, no problem.

**Review by varasev — COMMENTED** [review]
1) Let's automatically scroll the page up when we click on `All`, `Active`, or `To Finalize`.

2) When I click on `New Ballot`, I see the loading screen for a few seconds. On the previous version of DApp, there is no loading screen when clicking on `New Ballot`. Is there something new being loaded now?

3) Long description of a ballot isn't fully displayed on small screens (I used Chrome's responsive mode to discover it).

**Comment by varasev** [comment]
> 2) When I click on New Ballot, I see the loading screen for a few seconds. On the previous version of DApp, there is no loading screen when clicking on New Ballot. Is there something new being loaded now?

It seems the reason is that `New Ballot` button is not `NavLink`. Please make it use `NavLink` as other navigation links use (`All`, `Active`, and `To Finalize`).

**Comment by gabitoesmiapodo** [comment]
@varasev 

- Let's automatically scroll the page up when we click on All, Active, or To Finalize. -> Done.

- When I click on New Ballot, I see the loading screen for a few seconds. On the previous version of DApp, there is no loading screen when clicking on New Ballot. Is there something new being loaded now? It seems the reason is that New Ballot button is not NavLink. Please make it use NavLink as other navigation links use (All, Active, and To Finalize). -> Yes, you are right. Exchanged the link element for a NavLink. I did that too for the header and footer's logos, so everything should be smooth now.

- Long description of a ballot isn't fully displayed on small screens (I used Chrome's responsive mode to discover it). -> Fixed.

**Review by vbaranov — APPROVED** [review]

**Review by varasev — APPROVED** [review]

**Pull request merged**
