### PR TITLE
Update new ballot

### PR DESCRIPTION
**Pull request by ghost**
Problem:
Update new ballot form's design

Solution:
localhost_3000_poa-dapps-voting_new

### CODE REVIEW

**Comment by vbaranov** [comment]
@Dobriy-i what are the advantages of a new design?

**Comment by ghost** [comment]
@vbaranov i think main idea was to add types of ballot, it is better to ask @igorbarinov

**Comment by igorbarinov** [comment]
@vbaranov do you have any concerns about the design?

**Comment by vbaranov** [comment]
My concern is about this white space:

image 2018-03-12 19-05-13

If we keep in mind, that we will increase the number of ballots' types, I understand the idea to reorganize the form.
But if we will stay with 3 types of ballots, 20% of a new form will be empty every time.

**Comment by igorbarinov** [comment]
@vbaranov if we have more ballots type it will be filled.
Also, we could add a box with documentation about ballot type

**Comment by vbaranov** [comment]
Ok, makes sense. I will modify e2e test to touch new design.

**Review by vbaranov — CHANGES_REQUESTED** [review]
Left panel elements (ballot types) are not clickable:

bug

**Comment by vbaranov** [comment]
@Dobriy-i I can't merge because items in the left panel are frozen.

**Comment by ghost** [comment]
@vbaranov the main reason of this pr to do them, let's remove them and merge

**Comment by vbaranov** [comment]
@Dobriy-i remove what? did you see gif I attached?

**Comment by ghost** [comment]
Remove left panel's elements

**Comment by vbaranov** [comment]
@Dobriy-i let me know when PR will be ready to review/merge. It cannot be merged into production in this state.

**Comment by ghost** [comment]
@vbaranov it is done from my side, i don't know who will implement next, /cc @igorbarinov

**Comment by vbaranov** [comment]
@phahulin @rstormsf it is ready for review now:

voting_new_creation_form

**Review by rstormsf — APPROVED** [review]

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
