### PR TITLE
(Feature, Core) Some optimizations and "Load more ballots" button for "All" tab

### PR DESCRIPTION
**Pull request by varasev**
**(Mandatory) Description**
This PR makes `Voting DApp` display only first ten ballots and display "Load more ballots" button below the ballots list in "All" section:

image

It also adds optimization for reading validator metadata and efficiently usage of new smart contracts.

Relates to https://github.com/poanetwork/poa-dapps-voting/issues/118, https://github.com/poanetwork/poa-dapps-voting/issues/124, https://github.com/poanetwork/poa-dapps-voting/issues/128 and https://github.com/poanetwork/poa-dapps-voting/issues/132.

**(Mandatory) What is it: (Fix), (Feature) or (Refactor)**
(Feature)

### CODE REVIEW

**Review by vbaranov — CHANGES_REQUESTED** [review]
I suggest, that search should work on all cards, not only those cards displayed on the page. And "load more" button or should be hidden for search state or should account only items satisfying the search criteria

**Comment by varasev** [comment]
@vbaranov Ok, I fixed that in https://github.com/poanetwork/poa-dapps-voting/pull/139/commits/e5ce111130bde12271ad0e459723a65bdc52e270 and did some refactoring. Now the search works for all cards (even hidden by `Load more ballots` button) and the button takes into account only items satisfying the search criteria.

**Comment by varasev** [comment]
I've added a new commit https://github.com/poanetwork/poa-dapps-voting/pull/139/commits/287735aed83a59080d54a59b1d46dbc20ac9b77d collapsing `core` and `demo` branches.

**Review by vbaranov — COMMENTED** [review]
@varasev optimization and refactoring look good to me.
Was updated DApp checked with `poa-test-setup` scripts?

**Comment by varasev** [comment]
> Was updated DApp checked with `poa-test-setup` scripts?

@vbaranov Yes, it was. It can be checked with `poa-test-setup` from my repo: https://github.com/varasev/poa-test-setup - it is bound with all the latest changes (new smart contracts and updated Voting DApp and Validators DApp).

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
