### PR TITLE
(Feature) Add support for the Kovan testnet

### PR DESCRIPTION
**Pull request by varasev**
- (Mandatory) Description
These changes add support for the Kovan network. UI colors and logo have been copied from Sokol styles.

- (Mandatory) What is it: (Fix), (Feature), or (Refactor) in Title
(Feature)

### CODE REVIEW

**Review by vbaranov — COMMENTED** [review]
@varasev could you add a screenshot of a view of dapp when it is connected to Kovan to PR?

**Comment by varasev** [comment]
There are no ballots yet, of course, so the main page is empty:

image

image

**Review by vbaranov — COMMENTED** [review]
See https://github.com/poanetwork/poa-dapps-validators/pull/105#pullrequestreview-231624809

**Comment by varasev** [comment]
Done for Voting DApp:

image

**Review by vbaranov — APPROVED** [review]

**Comment by varasev** [comment]
@pashagonchar Please make a new logo for Kovan for the `Governance App`: https://github.com/varasev/poa-dapps-voting/blob/kovan-network/src/components/LogoKovan/logo.svg

And for the loading screen: https://github.com/varasev/poa-dapps-voting/blob/kovan-network/src/components/Loading/kovan.svg

**Comment by pashagonchar** [comment]
@varasev 
[kovan_governance_logo.zip](https://github.com/poanetwork/poa-dapps-voting/files/3147134/kovan_governance_logo.zip)
[kovan_loader.svg.zip](https://github.com/poanetwork/poa-dapps-voting/files/3147136/kovan_loader.svg.zip)

**Pull request merged**
